### ISSUE TITLE
So what's the point?

### ISSUE THREAD

**Issue by always-oles** [Pymmdrza/Rich-Address-Wallet#12]
Hi dev, would like to know - what's the point in scraping rich addresses from blockchain?
I mean, the trend goes to web3 socials, for example on https://debank.com/ you can check whales wallets, balance and stuff - but it doesn't help getting their mnemonics, right?
So what's the point knowing the person **X** has **Y** money at all?

**Comment by Pymmdrza** [comment]
> Hi dev, would like to know - what's the point in scraping rich addresses from blockchain? I mean, the trend goes to web3 socials, for example on https://debank.com/ you can check whales wallets, balance and stuff - but it doesn't help getting their mnemonics, right? So what's the point knowing the person **X** has **Y** money at all?

I use `BigQuery` by SQL, which I don't think there will be less people to pay because every update series that you see here extracts about `35GB` to `50GB` of data on the machines, and in the end, maybe from among them, the data of the entire blocks 1GB to 3GB are efficient and I will publish them here.
After extracting with Python script, I check all the data and sort the addresses according to their balance and publish them in different files with different types of addresses[`P2PKH`, `P2SH`, `P2WPKH`, `P2WSH`].
